Repository tzapu/WiFiManager, pull requests merged in 2018-06, with the labels that each got.

#584 Changed setAPCallback and setSaveConfigCallback to take std::function…
  WiFiManager.cpp
  WiFiManager.h
Labels: In Progress, QA, feature

#608 add CORS headers
  WiFiManager.cpp
  strings_en.h
Labels: feature

#571 enable all example builds for esp32
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .travis.yml
  README.md
Labels: Documentation
